# Generated by Django 3.1.7 on 2021-04-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
