# Generated by Django 3.1.7 on 2021-04-09 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0006_auto_20210405_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pinner',
            field=models.ManyToManyField(related_name='pinned_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
