# Generated by Django 3.1.7 on 2021-04-14 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0008_auto_20210410_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='voter',
            field=models.ManyToManyField(related_name='voted_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
